name: 'Close Pull Request'

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "This repository is READ-ONLY and does not accept PRs. If you have any questions, please feel free to contact us at contact@snicco.io"